#!/bin/sh

# Get the current branch name
branch_name=$(git rev-parse --abbrev-ref HEAD) 

# Get the last commit message
last_commit_message=$(git log -1 --pretty=%B)

# Append the branch name to the commit message
new_commit_message="$last_commit_message [$branch_name]"


# Write the new commit message to the prepare-commit-msg file
echo "$new_commit_message" > "$1"