name: CI Dart Console

on:
  push:
    paths:
      - 'dart_console_app/**'
      - '.github/workflows/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Change to Dart project directory
        run: cd dart_console_app

      - name: Install Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: 'latest'

      - name: Get dependencies
        run: |
          cd dart_console_app
          dart pub get

      - name: Build the Dart application
        run: |
          cd dart_console_app
          dart compile exe bin/main.dart -o bin/main

      - name: Run the Dart application
        run: |
          cd dart_console_app
          ./bin/main
          
      - run: echo "🍏 This job's status is ${{ job.status }}."