name: Deploy Static Web App to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'static-web-site/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

      - name: Log deployment success
        run: echo "Deployment completed successfully."